// Case studies, kept at the level of problem, approach and engineering judgement.
// No internal tool or programme names, business rules, figures, schedules or incidents.

export const cases = {
  'ops-platform': {
    title: 'An internal app that grew from a set of guides into the operations team’s daily tool',
    meta: {
      Role: 'Designed and built it; run it in production',
      Users: 'Operations, account management, support and leadership',
      Period: 'Apr 2026 to now',
      Stack: 'React, Vite, Netlify Functions, Supabase Postgres, Google sign-in',
      Status: 'In production',
    },
    tldr:
      'It started as written guides for the operations team. It now holds their dashboards, guides and forms, plus the scheduled jobs that keep the data fresh, behind a single company sign-in.',
    sections: [
      {
        h: 'Shape of the system',
        p: [
          'A React app on Netlify with serverless functions behind it. Some run on a schedule and some serve forms, approvals and live reads. Data lives in Postgres behind row-level security.',
          'The functions read from the company’s BI, CRM and helpdesk tools and write back out to the places people already work, such as Slack and email.',
        ],
      },
      {
        h: 'Running it',
        p: [
          'I also run it: deployments, credentials, access and fixes. Each time something went wrong I added a guard so it could not happen the same way again, such as regression tests and checks that run before a deploy.',
        ],
      },
    ],
    decisions: [
      'Compare complete periods only. Partial days are where dashboards mislead.',
      'Protect the data on the server, not just the page in the browser.',
      'Test the logic offline and build page layouts against mock data, so day-to-day work never needs production credentials.',
    ],
    results: [
      ['Where the team found numbers and procedures', 'Spreadsheets and chat threads', 'One internal app'],
      ['Data refresh', 'Manual exports', 'Scheduled, and runnable on demand'],
    ],
  },

  'merchant-onboarding': {
    title: 'Self-service onboarding for a new merchant vertical, built in 30 days',
    meta: {
      Role: 'Built the pipeline, working with the business team',
      Users: 'Sales, merchants, trainers and support',
      Period: 'Aug to Sep 2026',
      Stack: 'React, Netlify Functions, Zoho CRM, Notion, Slack',
      Status: 'In production',
    },
    tldr:
      'Setting up a new merchant took manual steps across several tools. I built a flow where the merchant fills in their details from one secure link, the team reviews them, and one publish step sets everything up across the internal systems.',
    sections: [
      {
        h: 'The flow',
        p: [
          'The merchant completes a secure, expiring link on their phone, with validation on the way in. After an internal review, publishing configures them through the company’s existing APIs, reads the settings back to confirm they were saved, and links the CRM records. The slow work runs in the background.',
          'The same flow produces the print artwork the merchant needs, as vector files generated by a small PDF writer I wrote for it.',
        ],
      },
    ],
    decisions: [
      'Confirm every write by reading it back, rather than trusting a success response.',
      'No automatic rollback across systems. A half-finished setup is visible and fixable; an automatic undo would be a second source of bugs.',
      'An offline test suite for the logic, so changes can be checked without touching production.',
    ],
    results: [
      ['Setting up a merchant', 'Manual steps across several tools', 'A form, a review and one publish'],
      ['Print artwork', 'Made by hand', 'Generated from the form'],
    ],
  },

  'reporting-stack': {
    title: 'Internal dashboards that agree with the BI tool',
    meta: {
      Role: 'Built the pipelines and reports',
      Users: 'Operations leads, account managers and leadership',
      Period: 'Jan 2026 to now',
      Stack: 'Tableau REST and VizQL Data Service, Zoho Analytics SQL, Supabase',
      Status: 'In production',
    },
    tldr:
      'If an internal dashboard disagrees with the official BI tool, people go back to the BI tool. I built a scheduled sync of BI and CRM data into Postgres and checked it until the totals matched, plus the SQL reports the team reviews performance with.',
    sections: [
      {
        h: 'Getting the numbers right',
        p: [
          'Totals are rebuilt from the underlying data model rather than read off a finished view, and weighted the same way the BI tool weights them, so the two agree.',
          'Reports that started as scripts I ran by hand became scheduled jobs once their definitions settled.',
        ],
      },
    ],
    decisions: [
      'Store only what a page reads, so queries stay fast.',
      'One definition of each period, reused everywhere.',
      'Exclusions are listed on the page, never applied silently.',
    ],
    results: [
      ['Internal totals against the BI tool', 'Not compared', 'Match'],
      ['Refresh', 'Manual exports', 'Scheduled'],
    ],
  },

  'crm-task-engine': {
    title: 'CRM automation that tells account managers where to look',
    meta: {
      Role: 'Designed and built the automation; maintain it',
      Users: 'Account managers and support',
      Period: 'Jan 2026 to now',
      Stack: 'Zoho CRM, Deluge, Slack API, AWS Lambda',
      Status: 'In production',
    },
    tldr:
      'Account managers used to find struggling venues by reading dashboards. I built CRM automation that does the watching: it reads each venue’s numbers, opens a task when something changes enough to matter, gives it to the right person, and closes it when things recover.',
    sections: [
      {
        h: 'Why it is harder than it sounds',
        p: [
          'A naive rule makes things worse. Flag every change and the same venue appears every day, the queue fills with noise, and people stop trusting it. Most of the work is in the controls that keep an automated queue worth reading.',
        ],
      },
    ],
    decisions: [
      'Ask whether someone is already working a venue before asking whether its numbers changed.',
      'A task cannot be closed without a note, so the queue doubles as a record of what was done.',
      'Write handover guides as I go, so someone else can maintain it.',
    ],
    results: [
      ['How venues needing attention were found', 'Dashboards and memory', 'Tasks created automatically, with an owner'],
      ['Duplicate and stale tasks', 'Common', 'Prevented'],
    ],
  },

  'incident-webhook': {
    title: 'Production alerts to support tickets in real time, exactly once',
    meta: {
      Role: 'Specified it, verified it against live data, and rolled it out',
      Users: 'Support agents',
      Period: 'Jul to Sep 2026',
      Stack: 'Netlify Functions, HMAC-SHA256, Zoho Desk REST API, Supabase',
      Status: 'In production',
    },
    tldr:
      'Production alerts used to reach the support desk through a spreadsheet that was polled. I replaced that with a signed webhook that creates the ticket directly, on the right account, and only once.',
    sections: [
      {
        h: 'How it works',
        p: [
          'Each request is signed and checked before anything happens. Each alert is claimed in a table that acts as a lock, so if the same event arrives twice the second copy updates the ticket instead of opening another. The account is matched exactly, and a rule-based classifier with tests sorts the ticket.',
        ],
      },
    ],
    decisions: [
      'Check the helpdesk API against live data before designing, then write a detailed spec and review the implementation against it.',
      'A rule-based classifier rather than a language model: predictable, testable and free per ticket.',
    ],
    results: [
      ['Latency', 'Polling', 'Real time'],
      ['Duplicate tickets on retry', 'Possible', 'Prevented'],
    ],
  },

  'reviews-impact': {
    title: 'Measuring what happens to merchants’ public ratings after they go live',
    meta: {
      Role: 'Built the pipeline and produced the reports',
      Users: 'Account managers and the merchants they share it with',
      Period: 'Jan to Aug 2026, monthly',
      Stack: 'Python, Playwright',
      Status: 'Monthly',
    },
    tldr:
      'A monthly before-and-after report on newly live merchants’ public ratings and review pace. Public review sites only show relative dates like “3 weeks ago”, so the hard part is building an honest baseline.',
    sections: [
      {
        h: 'The method',
        p: [
          'Only reviews that are certain to fall before go-live count towards the baseline, and merchants without enough history are left out rather than guessed at. The run is a short, documented pipeline: build the cohort, collect the histories, compute the metrics, produce the report.',
        ],
      },
    ],
    decisions: [
      'A collection run that returns nothing is treated as a failure, so a retry never overwrites good history.',
      'Reviews in every language are kept intact through the whole chain.',
      'Documented as a runbook, so someone else can run it.',
    ],
    results: [
      ['Producing the report', 'Manual work over several days', 'A short, repeatable run'],
    ],
  },
};
